build: false
services:
  - postgresql96
environment:
  global:
    PGUSER: postgres
    PGHOST: localhost
    PGPORT: 5432
    PGPASSWORD: Password12!
  matrix:
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3-x64
init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"
install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes
  - conda config --set changeps1 no
  - conda config --set channel_priority strict
  - conda info -a
  - "conda create -n testenv python=%PYTHON_VERSION% \
        fiona \
        flask \
        gdal \
        isodate \
        libgdal \
        networkx \
        numpy \
        pandas \
        psycopg2 \
        pyarrow \
        pytest \
        python-dateutil \
        rtree \
        shapely \
        xarray"
  - activate testenv
  - python setup.py develop
before_test:
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - createdb -e test_smif
test_script:
  - python setup.py test
