sudo: false
language: python
virtualenv:
  system_site_packages: true
cache:
  pip: true
  directories:
    - smif/app/node_modules
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - SKIP_GENERATE_AUTHORS=1
  - SKIP_WRITE_GIT_CHANGELOG=1
  matrix:
  - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="false"
  - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true"
install:
- source tests/travis_install.sh
- pip install -r test-requirements.txt -r requirements.txt
- python setup.py install
- nvm install 6.11.4
- nvm use 6.11.4
- cd $TRAVIS_BUILD_DIR/smif/app && npm install
script:
- cd $TRAVIS_BUILD_DIR && python setup.py test
- cd $TRAVIS_BUILD_DIR/smif/app && npm test
after_success:
- cd $TRAVIS_BUILD_DIR
- if [[ "$COVERAGE" == "true" ]]; then bash <(curl -s https://codecov.io/bash) -cF python || echo "failed"; fi
- cd $TRAVIS_BUILD_DIR/smif/app && npm run-script report
- if [[ "$COVERAGE" == "true" ]]; then bash <(curl -s https://codecov.io/bash) -cF javascript || echo "failed"; fi
notifications:
  email: false
deploy:
  provider: pypi
  user: willu47
  password:
    secure: MNNitxCYMRYG/AFTL+t3bAeR8z6Zda8ujUQEi1Nyvkug+Tl5rOX7Oz96GKr7XPfmTdVxSA2kBPBEjNmsAl8btSCl+5KyybqnBy00TpwzwLfmNZZvhLa54joOhli91a11g0pI8nrGXakSdzaeJhpoG2xb1hhEJ0i/18RUDH0JcjHLUW83f9AnY23lP/wnduto8ekwn9YtGWnc8QopFbA1VJK01ZBCHYsbAs/BhLXZrTI/KhFcnLQu4mLdSF7aONLlNaYUlKdLBRR6X7gczBiFQvy/05WHjohP5y8LbjnKGg9bEGtQzw+oNAa4FTrWClTBRvzWcZM+IDR5j87+FopBBnmuL2skLRV/uImyshtR+LC0bs6/M4ULSpe7jr5e4+bV6ptHtdJt6HcN5p3F4WnEusHCojx0l17ThtfF+vV16lHStfZUkqBu/MqqqW8CqbXDf8hZcCOXV11ImTHEQ8u0FEaIj85l95pG6ol+6ng1CuuTwHnIC3ZfMmqx/jnSyqsBib3QaSeNMxvIzgGyHD3ofMaunCF65yU1cRsiVVoHOe2gRs9hyjZKfPSA3jhPeCGMSLR9Pq2aSDiPH+Ri48/7XrqlRDh5o2V9nZ6vkkotSE24m9QXiGbRIct5q4UUQ4wPULTCNpVOxVOIClJeyexHDIZb0Z/vl/hjnrrl5csu0ZQ=
  on:
    tags: true
    all_branches: true
