sudo: false
language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
  - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
install:
- source tests/travis_install.sh
- pip install git+https://github.com/behave/behave
- pip install -r test-requirements.txt
before_script:
- git config --global user.email "william.usher@ouce.ox.ac.uk"
- git config --global user.name "Will Usher"
script:
- python setup.py develop
- python setup.py test
- python setup.py behave_test
after_success:
- if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
- apt
notifications:
  email: false
addons:
  apt:
    packages:
    - glpk
deploy:
  provider: pypi
  user: willu47
  password:
    secure: MNNitxCYMRYG/AFTL+t3bAeR8z6Zda8ujUQEi1Nyvkug+Tl5rOX7Oz96GKr7XPfmTdVxSA2kBPBEjNmsAl8btSCl+5KyybqnBy00TpwzwLfmNZZvhLa54joOhli91a11g0pI8nrGXakSdzaeJhpoG2xb1hhEJ0i/18RUDH0JcjHLUW83f9AnY23lP/wnduto8ekwn9YtGWnc8QopFbA1VJK01ZBCHYsbAs/BhLXZrTI/KhFcnLQu4mLdSF7aONLlNaYUlKdLBRR6X7gczBiFQvy/05WHjohP5y8LbjnKGg9bEGtQzw+oNAa4FTrWClTBRvzWcZM+IDR5j87+FopBBnmuL2skLRV/uImyshtR+LC0bs6/M4ULSpe7jr5e4+bV6ptHtdJt6HcN5p3F4WnEusHCojx0l17ThtfF+vV16lHStfZUkqBu/MqqqW8CqbXDf8hZcCOXV11ImTHEQ8u0FEaIj85l95pG6ol+6ng1CuuTwHnIC3ZfMmqx/jnSyqsBib3QaSeNMxvIzgGyHD3ofMaunCF65yU1cRsiVVoHOe2gRs9hyjZKfPSA3jhPeCGMSLR9Pq2aSDiPH+Ri48/7XrqlRDh5o2V9nZ6vkkotSE24m9QXiGbRIct5q4UUQ4wPULTCNpVOxVOIClJeyexHDIZb0Z/vl/hjnrrl5csu0ZQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
  skip_upload_docs: true
