name: 20170918_energy_water
description: Combined energy and water under central scenario
stamp: "2017-09-18T12:53:23+00:00"
timesteps:
- 2010
- 2015
- 2020
sos_model: energy_water
decision_module: ''
scenarios:
  population: Central Population (Medium)
  rainfall: Central Rainfall
narratives:
  technology:
  - High Tech Demand Side Management
