name: "Test Project"
scenario_sets:
- name: rainfall
  description: 'UK precipitation'
- name: population
  description: 'Growth in UK population'
narrative_sets:
- name: technology
  description: 'Describes the evolution of technology'
region_definitions:
# shared understanding of regions within the modelled area (e.g. GB)
- name: national
  description: ''
  filename: uk_nations_shp/regions.shp
- name: oxfordshire
  description: ''
  filename: oxfordshire/regions.geojson
interval_definitions:
# shared understanding of time intervals within a year
- name: annual
  description: ''
  filename: annual_intervals.csv
units:
scenarios:
# given input data, required values for every year of a model run
- name: 'Central Population (Low)'
  description: 'Central Population for the UK (Low)'
  scenario_set: population
  parameters:
  - name: population
    filename: population_low.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: people
- name: 'Central Population (Medium)'
  description: 'Central Population for the UK (Medium)'
  scenario_set: population
  parameters:
  - name: population
    filename: population_med.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: people
- name: 'Central Population (High)'
  description: 'Central Population for the UK (High)'
  scenario_set: population
  parameters:
  - name: population
    filename: population_low.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: people
- name: Central Rainfall
  description: 'Central Rainfall Scenario for the UK'
  scenario_set: rainfall
  parameters:
  - name: raininess
    filename: raininess.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: Ml
narratives:
- name: High Tech Demand Side Management
  description: 'High penetration of SMART technology on the demand side'
  filename: high_tech_dsm.yml
  narrative_set: technology
