interval_definitions:
- description: ''
  filename: annual_intervals.csv
  name: annual
name: Test Project
narrative_sets:
- description: Describes the evolution of technology
  name: technology
narratives:
- description: High penetration of SMART technology on the demand side
  filename: high_tech_dsm.yml
  name: High Tech Demand Side Management
  narrative_set: technology
region_definitions:
- description: ''
  filename: uk_nations_shp/regions.shp
  name: national
- description: ''
  filename: oxfordshire/regions.geojson
  name: oxfordshire
scenario_sets:
- description: Growth in UK population
  facets: null
  name: population
- description: Rainfall in the UK
  facets: null
  name: rainfall
scenarios:
- description: ''
  facets:
  - filename: raininess.csv
    name: central rainfall
    spatial_resolution: national
    temporal_resolution: annual
    units: m^3
  name: Central Rainfall
  scenario_set: rainfall
- description: ''
  facets:
  - filename: population_low.csv
    name: population
    spatial_resolution: national
    temporal_resolution: annual
    units: people
  name: Central Population (Low)
  scenario_set: population
- description: ''
  facets:
  - filename: population_med.csv
    name: population
    spatial_resolution: national
    temporal_resolution: annual
    units: people
  name: Central Population (Medium)
  scenario_set: population
- description: ''
  facets:
  - filename: population_high.csv
    name: population
    spatial_resolution: national
    temporal_resolution: annual
    units: people
  name: Central Population (High)
  scenario_set: population
units: units.txt
