name: energy_water_cp_cr
description: Combined energy and water under central scenarios
stamp: "2017-09-18T12:53:23+00:00"
timesteps:
- 2010
- 2015
- 2020
sos_model: energy_water
scenarios:
  population: population_med
  rainfall: central
narratives:
  technology:
  - high_tech_dsm
strategies:
- strategy: pre-specified-planning
  description: build_nuclear
  filename: build_nuke.yml
  model_name: energy_demand
