name: energy_waste
description: The future demand of energy for the UK
scenarios: # Select 0 or more of the scenario sets
- population
- water_sector_energy_demand
narratives: # Select 0 or more of the narrative sets
- technology
sector_models: # Select 1 or more of the sector models
- energy_demand
scenario_dependencies:
- source: population
  source_output: population
  sink: energy_demand
  sink_input: population
- source: water_sector_energy_demand
  source_output: energy_demand
  sink: energy_demand
  sink_input: energy_demand
model_dependencies: []
max_iterations: 100
convergence_absolute_tolerance: 1e-05
convergence_relative_tolerance: 1e-05
